#!/bin/bash

source ~/.local/share/sunhat/defaults/bash/shell
source ~/.local/share/sunhat/defaults/bash/aliases
if [ -f ~/.local/share/sunhat/defaults/bash/api_keys ]; then
  source ~/.local/share/sunhat/defaults/bash/api_keys
fi
