version: '3'
services:
  it_tools:
    image: corentinth/it-tools:latest
    container_name: it_tools
    hostname: it_tools.gib
    domainname: tools.${DOMAIN}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_PREFIX}.31
    ports:
      - 80:80
    env_file:
      - ../user_variables.env
    tty: true
    restart: unless-stopped

networks:
  ${NETWORK_NAME}:
    external: true
